### ISSUE TITLE
[BUG] neural-sparse-search Ingest documents error

### ISSUE THREAD

**Issue by sforce100** [opensearch-project/ml-commons#1822]
**What is the bug?**
I want to use neural sparse search feature, and i have my custom embedding model. So i want to connecting to externally hosted models. I create my connectors. Call _predict api success, but Ingest documents into the index failure.

**How can one reproduce the bug?**
1. create connector

```
curl -XPOST "https://localhost:9200/_plugins/_ml/connectors/_create" -ku admin:admin -H 'Content-Type: application/json' -d'
{
    "name": "listenai embedding lo 4",
    "description": "The connector to public embedding model service",
    "version": 1,
    "protocol": "http",
    "parameters": {
        "endpoint": "integration-api.listenai.com",
        "model": "embedding-v1"
    },
    "credential": {
        "apiKey": "xxxxx"
    },
    "actions": [
        {
            "action_type": "predict",
            "method": "POST",
            "url": "https://${parameters.endpoint}/v1/embedding",
            "headers": {
                "Authorization": "Bearer ${credential.apiKey}"
            },
            "request_body": "{ \"model\": \"${parameters.model}\", \"input\": ${parameters.input} }",
            "pre_process_function": "connector.pre_process.openai.embedding",
            "post_process_function": "connector.post_process.openai.embedding"
        }
    ]
}'
```
2. model register

```
curl -XPOST "https://localhost:9200/_plugins/_ml/models/_register" -ku admin:admin  -H 'Content-Type: application/json' -d'
{
    "name": "listenai-embedding",
    "function_name": "remote",
    "model_group_id": "apjmr4wBgPo_aoXhZrXv",
    "description": "test model",
    "connector_id": "j5gxtIwBgPo_aoXhObWb"
}'

```

3. model deploy
4. predict test

```
curl -XPOST "https://localhost:9200/_plugins/_ml/models/kZgxtIwBgPo_aoXhbbWL/_predict" -ku admin:admin  -H 'Content-Type: application/json' -d'
{
  "parameters": {
    "input": "You are a helpful assistant."
  }
}'
```
> predict response

```
{"inference_results":[{"output":[{"name":"sentence_embedding","data_type":"FLOAT32","shape":[1536],"data":[-0.027673654,-3.079282E-4,0.013836827,-0.035653338,-0.005410468,0.029258844,-0.010350753,-9.3029154E-4,-0.0072811265,-0.025255568,-0.0072072404,-0.014172672,-0.016510155,-0.005521297,-0.013971165,-0.038877454,0.042961333,-0.0031082483,0.01063958...........-2.6993567E-4,0.0057698227,-0.0027472146,-0.005803407,-0.010767201]}],"status_code":200}]}
```
5. create pipline

```
curl -XPUT "https://localhost:9200/_ingest/pipeline/nlp-ingest-pipeline-sparse" -ku admin:admin  -H 'Content-Type: application/json' -d'
{
  "description": "An sparse encoding ingest pipeline",
  "processors": [
    {
      "sparse_encoding": {
        "model_id": "kZgxtIwBgPo_aoXhbbWL",
        "field_map": {
          "passage_text": "passage_embedding"
        }
      }
    }
  ]
}'
```

6. create index

```
curl -XPUT "https://localhost:9200/my-nlp-index" -ku admin:admin -H 'Content-Type: application/json' -d'
{
  "settings": {
    "default_pipeline": "nlp-ingest-pipeline-sparse"
  },
  "mappings": {
    "properties": {
      "id": {
        "type": "text"
      },
      "passage_embedding": {
        "type": "rank_features"
      },
      "passage_text": {
        "type": "text"
      }
    }
  }
}'
```

7. insert document

```
curl -XPUT "https://localhost:9200/my-nlp-index1/_doc/1" -ku admin:admin -H 'Content-Type: application/json' -d'
{
  "passage_text": "Hello world",
  "id": "s1"
}'
```

> Got error response

```
{"error":{"root_cause":[{"type":"null_pointer_exception","reason":"Cannot invoke \"java.util.Map.containsKey(Object)\" because \"map\" is null"}],"type":"null_pointer_exception","reason":"Cannot invoke \"java.util.Map.containsKey(Object)\" because \"map\" is null"},"status":500}
```

**What is the expected behavior?**
Ingest documents into the index failure. and error logs:

```
[2023-12-29T08:13:10,200][WARN ][r.suppressed             ] [1d361f1188e4] path: /my-nlp-index1/_doc/1, params: {index=my-nlp-index1, id=1}

org.opensearch.ingest.IngestProcessorException: java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "map" is null

at org.opensearch.ingest.CompoundProcessor.newCompoundProcessorException(CompoundProcessor.java:251) ~[opensearch-2.11.1.jar:2.11.1]

at org.opensearch.ingest.CompoundProcessor.lambda$innerExecute$1(CompoundProcessor.java:173) [opensearch-2.11.1.jar:2.11.1]

at org.opensearch.neuralsearch.processor.SparseEncodingProcessor.lambda$doExecute$1(SparseEncodingProcessor.java:51) [opensearch-neural-search-2.11.1.0.jar:2.11.1.0]

at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:84) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.neuralsearch.ml.MLCommonsClientAccessor.lambda$retryableInferenceSentencesWithMapResult$1(MLCommonsClientAccessor.java:150) [opensearch-neural-search-2.11.1.0.jar:2.11.1.0]

at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.ml.client.MachineLearningNodeClient.lambda$getMlPredictionTaskResponseActionListener$7(MachineLearningNodeClient.java:195) [opensearch-ml-client-2.11.1.0.jar:?]

at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.ml.client.MachineLearningNodeClient.lambda$wrapActionListener$9(MachineLearningNodeClient.java:206) [opensearch-ml-client-2.11.1.0.jar:?]

at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:113) [opensearch-2.11.1.jar:2.11.1]

at org.opensearch.action.support.TransportAction$1.onResponse(TransportAction.java:107) [opensearch-2.11.1.jar:2.11.1]

at org.opensearch.core.action.ActionListener$6.onResponse(ActionListener.java:301) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.core.action.ActionListener$5.onResponse(ActionListener.java:268) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.core.action.ActionListener$5.onResponse(ActionListener.java:268) [opensearch-core-2.11.1.jar:2.11.1]

at org.opensearch.ml.task.MLPredictTaskRunner.predict(MLPredictTaskRunner.java:230) [opensearch-ml-2.11.1.0.jar:2.11.1.0]

at org.opensearch.ml.task.MLPredictTaskRunner.lambda$executeTask$4(MLPredictTaskRunner.java:194) [opensearch-ml-2.11.1.0.jar:2.11.1.0]

at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) [opensearch-2.11.1.jar:2.11.1]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]

at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "map" is null

at org.opensearch.neuralsearch.util.TokenWeightUtil.fetchListOfTokenWeightMap(TokenWeightUtil.java:54) ~[?:?]

at org.opensearch.neuralsearch.processor.SparseEncodingProcessor.lambda$doExecute$0(SparseEncodingProcessor.java:49) ~[?:?]

at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) ~[opensearch-core-2.11.1.jar:2.11.1]

... 17 more
```

**What is your host/environment?**
 - OS: docker
 - Opensearch Version 2.11.x
 - Plugins

**Comment by zhichao-aws** [comment]
> {"inference_results":[{"output":[{"name":"sentence_embedding","data_type":"FLOAT32","shape":[1536],"data":[-0.027673654,-3.079282E-4,0.013836827,-0.035653338,-0.005410468,0.029258844,-0.010350753,-9.3029154E-4,-0.0072811265,-0.025255568,-0.0072072404,-0.014172672,-0.016510155,-0.005521297,-0.013971165,-0.038877454,0.042961333,-0.0031082483,0.01063958...........-2.6993567E-4,0.0057698227,-0.0027472146,-0.005803407,-0.010767201]}],"status_code":200}]}

The response indicates this model is a dense embedding model. Sparse encoder should be used with sparse encoding models. The expected endpoint response should have payload of List<Map<String,Float>>. For example, for request ["sentence 1", "sentence 2"], endpoint response payload format should be 
```
[
  { "token 1": 1.23, "token2":2.34 ... },
  { "token 3": 1.23, "token4":2.34 ... }
]

```

**Comment by zhichao-aws** [comment]
If your model is a sparse encoding model, there should be some post-processing procedure.

**Comment by sforce100** [comment]
thx, my mistakes

**Comment by sforce100** [comment]
thx, my mistakes
