### ISSUE TITLE
[BUG] ResourceAlreadyExistsException reported when Creating the connector or ml-model index from two different thread/node at the same time

### ISSUE THREAD

**Issue by Zhangxunmt** [opensearch-project/ml-commons#1851]
**What is the bug?**
This issue happens for new cluster when there'are two create connector requests trying to create connector index at the same time. One request finished index creation successfully and the other one will fail with ResourceAlreadyExistsException which throws an error to the upper stream apps like AI-Flow. 

This error also potentially applies to other system index like ml-model, task, etc. 

Error message:
~~~
[2024-01-09T10:03:44,835][ERROR][o.o.m.e.i.MLIndicesHandler] [smoketestnode] Failed to create index .plugins-ml-connector
org.opensearch.ResourceAlreadyExistsException: index [.plugins-ml-connector/9oekSeBIQvSC1t3VA5sciQ] already exists
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:226) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1246) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:394) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:449) ~[opensearch-3.0.0.jar:3.0.0] 
        at org.opensearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:355) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:67) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:882) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:434) ~[opensearch-3.0.0.jar:3.0.0]
        at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:301) [opensearch-3.0.0.jar:3.0.0]
~~~
**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by austintlee** [comment]
@HenryL27 I think the fix for this issue can work for the memory index?

**Comment by Zhangxunmt** [comment]
Yes you are right. This issue does not apply to memory indices. I checked that in the PR already. @austintlee
