### ISSUE TITLE
[BUG] Remove the index .plugins-ml-model manually will cause unexpected errors

### ISSUE THREAD

**Issue by gaobinlong** [opensearch-project/ml-commons#1860]
**What is the bug?**

This morning there are too many error logs in our cluster:
```
opensearch-cluster-master-2 opensearch [2024-01-12T02:01:40,390][ERROR][o.o.m.c.MLSyncUpCron     ] [opensearch-cluster-master-2] Failed to init model index
opensearch-cluster-master-2 opensearch java.lang.IllegalArgumentException: mapper [model_version] cannot be changed from type [text] to [keyword]
```
, after diving deep on it, we found that someone removed the system index `.plugins-ml-model` manually yesterday, and the index was created automatically by the code, but the mappings of the new index is not consistent with the pre-defined mappings in the code, I see that we try to [update the mapping](https://github.com/opensearch-project/ml-commons/blob/19c93b153d6e86eeaf42409ac4330c14f76b3aeb/ml-algorithms/src/main/java/org/opensearch/ml/engine/indices/MLIndicesHandler.java#L122) of that system index when the system index already exists, this is a problem because most of the data type cannot be changed, like change `text` to `keyword` , so we see the `IllegalArgumentException` error.

In my local env, I reproduced this problem easily, when deploying a model and delete the index .`plugins-ml-model` suddenly,  a new index was created automatically when calling the update api to update the document in that index, the new index has wrong mappings:
```
      "model_version": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "name": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
```

I see that there are many places that can trigger re-creating the index, see the log:
![image](https://github.com/opensearch-project/ml-commons/assets/15811131/d6b30348-74ba-4c88-a750-0e27743e2b25)
, so we may do something to  prevent this problem happening, like checking the index existing or not before calling the index/update/bulk API, or adding a index template for the system index.

**How can one reproduce the bug?**
1. Deploy a model which will take a long time to execute and then delete the index .`plugins-ml-model` suddenly

**What is the expected behavior?**
The system index always has correct mappings.

**What is your host/environment?**
 - OS: [MacOS]
 - Version [3.0.0]
 - Plugins: ml-commons, skills, flow-framework

**Comment by Zhangxunmt** [comment]
Can you post the error message stack? The picture of trigger re-creating the index cannot load from my side.

**Comment by gaobinlong** [comment]
> @gaobinlong what is the update api you called to reproduce this problem? If it's update Model API, it should throw an error showing that it failed to find the model to update.
> 
> ```
>  I reproduced this problem easily, when deploying a model and delete the index .plugins-ml-model suddenly, a new index was created automatically when calling the update api to update the document in that index, the new index has wrong mappings:
> ```

Register a model and set `deploy` to true, in the meantime delete the system index `.plugins-ml-model`:
```
POST /_plugins/_ml/models/_register?deploy=true
{
  "name": "huggingface/sentence-transformers/all-MiniLM-L12-v2",
  "version": "1.0.1",
  "model_format": "TORCH_SCRIPT"
}
```
, I think there are many places can trigger re-creating the system index automatically, such as calling the undeploy API after deleting the system index `.plugins-ml-model`, if the system index is created automatically by index or bulk API, the mappings are not correct, that's the root cause, the IllegalArgumentException `cannot be changed from type [text] to [keyword]` is the result.

**Comment by gaobinlong** [comment]
> Can you post the error message stack? The picture of trigger re-creating the index cannot load from my side.

	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:242) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:204) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:212) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:301) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:434) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:882) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.execute(MetadataMappingService.java:244) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.applyRequest(MetadataMappingService.java:283) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:305) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.Mapping.merge(Mapping.java:130) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:347) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:584) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:352) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:625) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:77) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:114) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
java.lang.IllegalArgumentException: mapper [model_version] cannot be changed from type [text] to [keyword]
[2024-01-12T08:40:50,948][ERROR][o.o.m.c.MLSyncUpCron     ] [opensearch-cluster-master-2] Failed to init model index

**Comment by Zhangxunmt** [comment]
We can change to throw an exception if the model index is deleted in middle of any operation that requires documents updates in the index. Deleting the system in a sudden may not be expected though.

**Comment by Zhangxunmt** [comment]
~~~
[2024-01-23T19:32:55,508][INFO ][o.o.c.m.MetadataDeleteIndexService] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] [.plugins-ml-model/2rHe9LKqS_Wpzlkm8H2ccQ] deleting index
[2024-01-23T19:32:55,615][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Detected cluster change event for destination migration
[2024-01-23T19:32:55,617][ERROR][o.o.m.m.MLModelManager   ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Failed to index model chunk Ti_PN40BhyTBNj1prMPb_2
org.opensearch.index.IndexNotFoundException: no such index [.plugins-ml-model]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:939) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:1120) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:380) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.postAdded(ClusterStateObserver.java:257) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.service.ClusterApplierService$1.run(ClusterApplierService.java:320) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245) [opensearch-2.11.0.jar:2.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[2024-01-23T19:32:55,628][ERROR][o.o.m.m.MLModelManager   ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Failed to index model chunk Ti_PN40BhyTBNj1prMPb_2
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "doesVersionCreateModelGroup" is null
	at org.opensearch.ml.model.MLModelManager.deleteOrUpdateModelGroup(MLModelManager.java:878) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.deleteModel(MLModelManager.java:872) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.lambda$registerModel$37(MLModelManager.java:770) ~[?:?]
	at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.bulk.TransportSingleItemBulkWriteAction.lambda$wrapBulkResponse$0(TransportSingleItemBulkWriteAction.java:86) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$6.onResponse(ActionListener.java:301) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:691) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.bulk.TransportBulkAction$BulkOperation$1.onFailure(TransportBulkAction.java:685) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$6.onFailure(ActionListener.java:311) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishAsFailed(TransportReplicationAction.java:1140) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:939) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:1120) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:380) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.postAdded(ClusterStateObserver.java:257) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.service.ClusterApplierService$1.run(ClusterApplierService.java:320) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245) [opensearch-2.11.0.jar:2.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[2024-01-23T19:32:55,629][WARN ][o.o.m.t.MLTaskManager    ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Can't find task in cache: Si_PN40BhyTBNj1pq8Nr
[2024-01-23T19:32:55,630][WARN ][o.o.a.b.TransportShardBulkAction] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] unexpected error during the primary phase for action [indices:data/write/bulk[s]], request [BulkShardRequest [[.plugins-ml-model][0]] containing [index {[.plugins-ml-model][Ti_PN40BhyTBNj1prMPb_2], source[n/a, actual length: [12.7mb], max length: 2kb]}] and a refresh]
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "doesVersionCreateModelGroup" is null
	at org.opensearch.ml.model.MLModelManager.deleteOrUpdateModelGroup(MLModelManager.java:878) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.deleteModel(MLModelManager.java:872) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.lambda$registerModel$37(MLModelManager.java:770) ~[?:?]
	at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) ~[opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) ~[opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:84) ~[opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$6.onResponse(ActionListener.java:301) ~[opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:691) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.bulk.TransportBulkAction$BulkOperation$1.onFailure(TransportBulkAction.java:685) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$6.onFailure(ActionListener.java:311) ~[opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:122) ~[opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishAsFailed(TransportReplicationAction.java:1140) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:939) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:1120) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:380) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.postAdded(ClusterStateObserver.java:257) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.cluster.service.ClusterApplierService$1.run(ClusterApplierService.java:320) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:849) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:282) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:245) [opensearch-2.11.0.jar:2.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[2024-01-23T19:33:02,299][INFO ][o.o.j.s.JobSweeper       ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Running full sweep
[2024-01-23T19:33:05,595][ERROR][o.o.m.m.MLModelManager   ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Failed to index chunk file
org.opensearch.ml.common.exception.MLException: Failed to save model chunk
	at org.opensearch.ml.model.MLModelManager.lambda$registerModel$38(MLModelManager.java:719) ~[?:?]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.ml.engine.ModelHelper.lambda$downloadAndSplit$3(ModelHelper.java:238) [opensearch-ml-algorithms-2.11.0.0-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) [?:?]
	at org.opensearch.ml.engine.ModelHelper.downloadAndSplit(ModelHelper.java:221) [opensearch-ml-algorithms-2.11.0.0-SNAPSHOT.jar:?]
	at org.opensearch.ml.model.MLModelManager.registerModel(MLModelManager.java:697) [opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.ml.model.MLModelManager.lambda$registerModelFromUrl$31(MLModelManager.java:672) [opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:78) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.0.jar:2.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[2024-01-23T19:33:05,612][ERROR][o.o.m.m.MLModelManager   ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Failed to index chunk file
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "doesVersionCreateModelGroup" is null
	at org.opensearch.ml.model.MLModelManager.deleteOrUpdateModelGroup(MLModelManager.java:878) ~[opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.ml.model.MLModelManager.deleteModel(MLModelManager.java:872) ~[opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.ml.model.MLModelManager.lambda$registerModel$39(MLModelManager.java:778) [opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) ~[opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:84) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.ml.engine.ModelHelper.lambda$downloadAndSplit$3(ModelHelper.java:238) ~[opensearch-ml-algorithms-2.11.0.0-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at org.opensearch.ml.engine.ModelHelper.downloadAndSplit(ModelHelper.java:221) [opensearch-ml-algorithms-2.11.0.0-SNAPSHOT.jar:?]
	at org.opensearch.ml.model.MLModelManager.registerModel(MLModelManager.java:697) [opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.ml.model.MLModelManager.lambda$registerModelFromUrl$31(MLModelManager.java:672) [opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:78) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.0.jar:2.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[2024-01-23T19:33:05,614][ERROR][o.o.m.m.MLModelManager   ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Failed to index model meta doc
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "doesVersionCreateModelGroup" is null
	at org.opensearch.ml.model.MLModelManager.deleteOrUpdateModelGroup(MLModelManager.java:878) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.deleteModel(MLModelManager.java:872) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.lambda$registerModel$39(MLModelManager.java:778) [opensearch-ml-2.11.0.0-SNAPSHOT.jar:2.11.0.0-SNAPSHOT]
	at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.ml.engine.ModelHelper.downloadAndSplit(ModelHelper.java:246) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.registerModel(MLModelManager.java:697) ~[?:?]
	at org.opensearch.ml.model.MLModelManager.lambda$registerModelFromUrl$31(MLModelManager.java:672) ~[?:?]
	at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.11.0.jar:2.11.0]
	at org.opensearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:78) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.11.0.jar:2.11.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.11.0.jar:2.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[2024-01-23T19:33:05,615][WARN ][o.o.m.t.MLTaskManager    ] [dev-dsk-xunzh-2c-b57bd588.us-west-2.amazon.com] Can't find task in cache: Si_PN40BhyTBNj1pq8Nr
~~~

**Comment by gaobinlong** [comment]
> Couldn't duplicate the error case from my end. After registering/deploying a pre-trained hugging-face model, I deleted the ml-model index with system level permission but the error is "org.opensearch.index.IndexNotFoundException: no such index [.plugins-ml-model]" which is expected.
> 
> Besides, the ".plugins-ml-model" is a system index so customer has no permission to delete it. Deleting the system index can be considered as a mis-operation as well, so closing this issue. Feel free to reopen if this issue happen again at somewhere else.

When you delete the index and see the error `IndexNotFoundException`, is that means the index has been delete yet? Why this is expected?

In addition, if the cluster has no security plugin, anyone can delete the system index.

I think the problem we should resolve is that we should prevent that system index from being created automatically and with wrong mappings.
