### ISSUE TITLE
[BUG] connector throws error when doing predict.

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/ml-commons#1971]
**What is the bug?**
`ConnectorUtils.java` is throwing error that the input payload is not a valid JSON.

**How can one reproduce the bug?**
1. Go to Chatbot
2. Start to ask any question 
3. See error

**What is the expected behavior?**
Agent framework should response with correct answer.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/ml-commons/assets/13493605/77b077bb-02c2-4d10-88c9-a8049d05ea25)
```
[2024-01-31T17:19:38,067][ERROR][o.o.m.e.t.AgentTool      ] [bcd07460f620] Failed to run agent RD81Xo0B1rK8biFXOHid
java.lang.IllegalArgumentException: Invalid payload: {LARGE_PROMPT}
 at org.opensearch.ml.common.connector.HttpConnector.createPredictPayload(HttpConnector.java:294) ~[opensearch-ml-common-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.ml.engine.algorithms.remote.RemoteConnectorExecutor.preparePayloadAndInvokeRemoteModel(RemoteConnectorExecutor.java:120) ~[opensearch-ml-algorithms-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.ml.engine.algorithms.remote.RemoteConnectorExecutor.executePredict(RemoteConnectorExecutor.java:74) ~[opensearch-ml-algorithms-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.ml.engine.algorithms.remote.RemoteModel.predict(RemoteModel.java:61) ~[opensearch-ml-algorithms-3.0.0.0-SNAPSHOT.jar:?]
	at org.opensearch.ml.task.MLPredictTaskRunner.lambda$predict$5(MLPredictTaskRunner.java:222) [opensearch-ml-3.0.0.0-SNAPSHOT.jar:3.0.0.0-SNAPSHOT]
	at org.opensearch.ml.model.MLModelManager.trackPredictDuration(MLModelManager.java:1774) ~[opensearch-ml-3.0.0.0-SNAPSHOT.jar:3.0.0.0-SNAPSHOT]
	at org.opensearch.ml.task.MLPredictTaskRunner.predict(MLPredictTaskRunner.java:222) [opensearch-ml-3.0.0.0-SNAPSHOT.jar:3.0.0.0-SNAPSHOT]
	at org.opensearch.ml.task.MLPredictTaskRunner.lambda$executeTask$4(MLPredictTaskRunner.java:194) [opensearch-ml-3.0.0.0-SNAPSHOT.jar:3.0.0.0-SNAPSHOT]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:854) [opensearch-3.0.0.jar:3.0.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

**Do you have any additional context?**
Add any other context about the problem.

**Comment by SuZhou-Joe** [comment]
Should have something to do with #1954

**Comment by ylwu-amzn** [comment]
@SuZhou-Joe should be fixed in https://github.com/opensearch-project/ml-commons/pull/1970, can you test and confirm?

**Comment by SuZhou-Joe** [comment]
@ylwu-amzn Confirmed, it is fixed.
