### ISSUE TITLE
Flaky Test NeuralQueryEnricherProcessorIT

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/ml-commons#2381]
**What is the bug?**

when merging https://github.com/opensearch-project/ml-commons/pull/2378 found a flaky test in `NeuralQueryEnricherProcessorIT` 

**How can one reproduce the bug?**
```
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.neuralsearch.processor.NeuralQueryEnricherProcessorIT.testNeuralQueryEnricherProcessor_whenNoModelIdPassed_thenSuccess" -Dtests.seed=8CD5F0F23E3C4488 -Dtests.security.manager=false -Dtests.locale=zh-Hans-CN -Dtests.timezone=Asia/Makassar -Druntime.java=21
  2> org.opensearch.client.ResponseException: method [POST], host [https://127.0.0.1:44495/], URI [/my-nlp-index/_search?size=2], status line [HTTP/2.0 400 Bad Request]
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Model not ready yet. Please deploy the model first."}],"type":"illegal_argument_exception","reason":"Model not ready yet. Please deploy the model first."},"status":400}
        at __randomizedtesting.SeedInfo.seed([8CD5F0F23E3C4488:D63CE89FF1D4BCD9]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:385)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:355)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:330)
        at app//org.opensearch.neuralsearch.BaseNeuralSearchIT.search(BaseNeuralSearchIT.java:513)
        at app//org.opensearch.neuralsearch.BaseNeuralSearchIT.search(BaseNeuralSearchIT.java:467)
        at app//org.opensearch.neuralsearch.BaseNeuralSearchIT.search(BaseNeuralSearchIT.java:455)
        at app//org.opensearch.neuralsearch.BaseNeuralSearchIT.search(BaseNeuralSearchIT.java:434)
        at app//org.opensearch.neuralsearch.BaseNeuralSearchIT.search(BaseNeuralSearchIT.java:415)
```
**What is the expected behavior?**
CI test passed

**What is your host/environment?**
 - OS: 
 - Version 2.14
 - Plugins ml commons

**Comment by ylwu-amzn** [comment]
@mingshl  Is this the same bug in this issue https://github.com/opensearch-project/ml-commons/issues/2382 ?

**Comment by mingshl** [comment]
@ylwu-amzn seems like the same bug, closing this issue to avoid duplication, Please refer to https://github.com/opensearch-project/ml-commons/issues/2382 for future reference.
