### ISSUE TITLE
[BUG] Flaky Test "org.opensearch.ml.action.trainpredict.TrainAndPredictITTests.testTrainAndPredictWithEmptyDataset_KMeans" 

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/ml-commons#241]
**Describe the bug**
Test Failed on commit to main https://github.com/opensearch-project/ml-commons/runs/5651851540?check_suite_focus=true
Seems to be flaky on JDK 14 as it passes after re-running. `org.opensearch.ml.action.trainpredict.TrainAndPredictITTests.testTrainAndPredictWithEmptyDataset_KMeans`

```
org.opensearch.ml.action.trainpredict.TrainAndPredictITTests > testTrainAndPredictWithEmptyDataset_KMeans FAILED
    java.lang.AssertionError: 
REPRODUCE WITH: ./gradlew ':opensearch-ml-plugin:test' --tests "org.opensearch.ml.action.trainpredict.TrainAndPredictITTests.testTrainAndPredictWithEmptyDataset_KMeans" -Dtests.seed=3D47449C11AF025E -Dtests.security.manager=false -Dtests.locale=es-AR -Dtests.timezone=America/Argentina/Jujuy -Druntime.java=14
    Expected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing "No document found")
         but: an instance of java.lang.IllegalArgumentException <org.junit.runners.model.MultipleFailureException: There were 2 errors:
      org.opensearch.transport.NodeDisconnectedException([node_s1][127.0.0.1:39709][cluster:admin/opensearch/ml/trainAndPredict] disconnected)
      org.opensearch.discovery.MasterNotDiscoveredException(null)> is a org.junit.runners.model.MultipleFailureException
    Stacktrace was: org.junit.runners.model.MultipleFailureException: There were 2 errors:
      org.opensearch.transport.NodeDisconnectedException([node_s1][127.0.0.1:39709][cluster:admin/opensearch/ml/trainAndPredict] disconnected)
      org.opensearch.discovery.MasterNotDiscoveredException(null)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1006)
    	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
    	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
    	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
    	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    	at java.base/java.lang.Thread.run(Thread.java:832)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.junit.rules.ExpectedException.handleException(ExpectedException.java:252)
        at org.junit.rules.ExpectedException.access$000(ExpectedException.java:106)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:241)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:832)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=432, name=opensearch[node_s1][transport_worker][T#2], state=RUNNABLE, group=TGRP-TrainAndPredictITTests]

**Comment by ylwu-amzn** [comment]
`MasterNotDiscoveredException` this failure caused by the test cluster not ready, not caused by the test itself. Seems CI test server not so stable. 

Saw another failure https://github.com/opensearch-project/ml-commons/runs/5664575875?check_suite_focus=true , this one caused by circuit breaker exception

```
org.opensearch.ml.action.trainpredict.TrainAndPredictITTests > testTrainAndPredictWithEmptyDataset_KMeans FAILED
    java.lang.AssertionError: 

    Expected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing "No document found")
         but: an instance of java.lang.IllegalArgumentException <org.opensearch.ml.common.exception.MLLimitExceededException: Circuit breaker is open> is a org.opensearch.ml.common.exception.MLLimitExceededException
    Stacktrace was: org.opensearch.ml.common.exception.MLLimitExceededException: Circuit breaker is open
    	at org.opensearch.ml.task.MLTaskRunner.run(MLTaskRunner.java:81)
    	at org.opensearch.ml.action.trainpredict.TransportTrainAndPredictionTaskAction.doExecute(TransportTrainAndPredictionTaskAction.java:38)
    	at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:194)
    	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:[169](https://github.com/opensearch-project/ml-commons/runs/5664575875?check_suite_focus=true#step:4:169))
    	at org.opensearch.action.support.TransportAction.execute(TransportAction.java:97)
    	at org.opensearch.client.node.NodeClient.executeLocally(NodeClient.java:108)
    	at org.opensearch.client.node.NodeClient.doExecute(NodeClient.java:95)
    	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:425)
    	at org.opensearch.client.FilterClient.doExecute(FilterClient.java:81)
    	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:425)
    	at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:412)
    	at org.opensearch.ml.action.MLCommonsIntegTestCase.trainAndPredict(MLCommonsIntegTestCase.java:120)
    	at org.opensearch.ml.action.trainpredict.TrainAndPredictITTests.testTrainAndPredictWithEmptyDataset_KMeans(TrainAndPredictITTests.java:65)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:[175](https://github.com/opensearch-project/ml-commons/runs/5664575875?check_suite_focus=true#step:4:175)0)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
    	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
    	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
```
