### ISSUE TITLE
[BUG] Flaky integration test

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/ml-commons#2565]
**What is the bug?**
The below IT is flaky: https://github.com/opensearch-project/ml-commons/actions/runs/9540553655/job/26297294535?pr=2500#step:6:2743, need to fix this.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by rbhavna** [comment]
Below is the error we are seeing:
```org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT > testMLInferenceProcessorLocalModelObjectField FAILED
    org.opensearch.client.ResponseException: method [POST], host [http://[::1]:40201], URI [/_plugins/_ml/models/null/_deploy], status line [HTTP/1.1 404 Not Found]
    {"error":{"root_cause":[{"type":"status_exception","reason":"Failed to find model"}],"type":"status_exception","reason":"Failed to find model"},"status":404}
        at __randomizedtesting.SeedInfo.seed([1710F9F105660AC2:A819478207165E21]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:385)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:355)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:330)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:179)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:152)
        at app//org.opensearch.ml.utils.TestHelper.makeRequest(TestHelper.java:141)
        at app//org.opensearch.ml.rest.RestMLRemoteInferenceIT.deployRemoteModel(RestMLRemoteInferenceIT.java:1043)
        at app//org.opensearch.ml.rest.MLCommonsRestTestCase.registerRemoteModel(MLCommonsRestTestCase.java:1010)
        at app//org.opensearch.ml.rest.RestMLInferenceIngestProcessorIT.setup(RestMLInferenceIngestProcessorIT.java:116)`

**Comment by dblock** [comment]
[Catch All Triage, attendees [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/lukas-vlcek/), [4](https://github.com/rafaelma), [5](https://github.com/krisfreedain), [6](https://github.com/gargrajat), [7](https://github.com/andrross)]
