### ISSUE TITLE
[BUG] unable to run knn search with neural query on OS 2.16.0

### ISSUE THREAD

**Issue by IanMenendez** [opensearch-project/ml-commons#2838]
**What is the bug?**
Searching with neural query brings down OS 2.16.0.

This is happening in OS 2.16.0 Image `FROM opensearchproject/opensearch:2.16.0`  but not in 2.15.0 or lower

**How to reproduce the bug?**
1. Upload and deploy ML model
```
We have a custom transformers model but you can upload another one with:

POST /_plugins/_ml/models/_register
{
  "name": "huggingface/sentence-transformers/msmarco-distilbert-base-tas-b",
  "version": "1.0.2",
  "model_group_id": "Z1eQf4oB5Vm0Tdw8EIP2",
  "model_format": "TORCH_SCRIPT"
}

POST /_plugins/_ml/models/dxyObJEBGnTvwYNln7p8/_deploy

```

3. Create index with settings knn = true and an ingest pipeline for the model

```
PUT _ingest/pipeline/test
{
  "description": "",
  "processors": [
    {
      "text_embedding": {
        "model_id": "dxyObJEBGnTvwYNln7p8",
        "field_map": {
          "text": "text_embedding"
        }
      }
    }
  ]
}

PUT /testing
{
  "settings": {
    "index.knn": true,
    "index.default_pipeline": "test"
  },
  "mappings": {
    "properties": {
      "text": {
        "type": "text"
      },
      "text_embedding": {
        "type": "knn_vector",
        "dimension": 2
      }
    }
  }
}

```

5. ingest some docs
POST /testing/_doc
```
{
  "text": "testing knn"
}
```
6. Search with a neural query

```
POST /testing/_search
{
  "query": {
    "neural": {
      "text_embedding": {
        "model_id": "dxyObJEBGnTvwYNln7p8",
        "query_text": "testing_neural"
      }
    }
  }
}
```

7. Cluster goes down with: 
```
opensearch-node2       | fatal error in thread [opensearch[opensearch-node2][refresh][T#3]], exiting
opensearch-node2       | java.lang.UnsatisfiedLinkError: /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_common.so: /usr/share/opensearch/data/ml_cache/pytorch/1.13.1-cpu-precxx11-linux-x86_64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_util.so)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
opensearch-node2       | 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2451)
opensearch-node2       | 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
opensearch-node2       | 	at java.base/java.lang.System.loadLibrary(System.java:2063)
opensearch-node2       | 	at org.opensearch.knn.jni.JNICommons.lambda$static$0(JNICommons.java:26)
opensearch-node2       | 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
opensearch-node2       | 	at org.opensearch.knn.jni.JNICommons.<clinit>(JNICommons.java:25)
opensearch-node2       | 	at org.opensearch.knn.index.codec.transfer.VectorTransferFloat.transfer(VectorTransferFloat.java:68)
opensearch-node2       | 	at org.opensearch.knn.index.codec.transfer.VectorTransferFloat.close(VectorTransferFloat.java:59)
opensearch-node2       | 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getPair(KNNCodecUtil.java:61)
opensearch-node2       | 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.addKNNBinaryField(KNN80DocValuesConsumer.java:147)
opensearch-node2       | 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.addBinaryField(KNN80DocValuesConsumer.java:87)
opensearch-node2       | 	at org.apache.lucene.index.BinaryDocValuesWriter.flush(BinaryDocValuesWriter.java:132)
opensearch-node2       | 	at org.apache.lucene.index.IndexingChain.writeDocValues(IndexingChain.java:424)
opensearch-node2       | 	at org.apache.lucene.index.IndexingChain.flush(IndexingChain.java:282)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:445)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:496)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriter.maybeFlush(DocumentsWriter.java:450)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:643)
opensearch-node2       | 	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:578)
opensearch-node2       | 	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:381)
opensearch-node2       | 	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:355)
opensearch-node2       | 	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:345)
opensearch-node2       | 	at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:112)
opensearch-node2       | 	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:170)
opensearch-node2       | 	at org.opensearch.index.engine.OpenSearchReaderManager.refreshIfNeeded(OpenSearchReaderManager.java:72)
opensearch-node2       | 	at org.opensearch.index.engine.OpenSearchReaderManager.refreshIfNeeded(OpenSearchReaderManager.java:52)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:240)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:433)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:413)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine.refresh(InternalEngine.java:1865)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:1844)
opensearch-node2       | 	at org.opensearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:4648)
opensearch-node2       | 	at org.opensearch.index.IndexService.maybeRefreshEngine(IndexService.java:1157)
opensearch-node2       | 	at org.opensearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1301)
opensearch-node2       | 	at org.opensearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:159)
opensearch-node2       | 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:882)
opensearch-node2       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
opensearch-node2       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
opensearch-node2       | 	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**What is the expected behavior?**
Dont crash and perform a search

**What is your host/environment?**
Docker with `FROM opensearchproject/opensearch:2.16.0` Image

NOTE: This issue only happens the first time you run a neural query. After running a neural query sometime after the first one, the cluster seems to get the libraries. I do not know what was changed from OS 2.15 to 2.16

**Comment by Zhangxunmt** [comment]
what is the operation system you used for producing this error? @IanMenendez

**Comment by IanMenendez** [comment]
> what is the operation system you used for producing this error? @IanMenendez

@Zhangxunmt I replicated the issue in the OS 2.16  docker container `FROM opensearchproject/opensearch:2.16.0`

But It's also happening on my local machine with `Linux Mint 21.1`

**Comment by ylwu-amzn** [comment]
From the error 
`opensearch-node2       | java.lang.UnsatisfiedLinkError: /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_common.so: /usr/share/opensearch/data/ml_cache/pytorch/1.13.1-cpu-precxx11-linux-x86_64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_util.so)`

It's KNN plugin can't find `libopensearchknn_common.so`. Ask KNN guys to help take a look

**Comment by IanMenendez** [comment]
@ylwu-amzn 
I can confirm that using the predict API directly does not crash the cluster. 

Using neural query crashes the cluster

**Comment by ylwu-amzn** [comment]
@navneet1v , as predict API works correctly, I think the issue is from KNN, the log also shows it's related with KNN `java.lang.UnsatisfiedLinkError: /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_common.so` , can KNN team help take a look ? 

I have no permission to k-NN plugin repo, so can't transfer it to k-NN repo

**Comment by yuye-aws** [comment]
Also meet with the same issue. Can you take a look @navneet1v @martin-gaievski ?

**Comment by yuye-aws** [comment]
@IanMenendez Maybe you can try this workaround: https://forum.opensearch.org/t/issue-with-opensearch-knn/12633/3

**Comment by martin-gaievski** [comment]
@yuye-aws this error looks specific to native knn engines. Can you check which one you're using, if it's one of native ones (faiss or nmslib) can you try defining `lucene` as your knn engine.

**Comment by ylwu-amzn** [comment]
@martin-gaievski , can you transfer this issue to k-nn plugin repo ? I think change to lucene can work , but we should also support other two native engines. Suggest K-NN team to try this, seems very easy to reproduce.

**Comment by yuye-aws** [comment]
> @yuye-aws this error looks specific to native knn engines. Can you check which one you're using, if it's one of native ones (faiss or nmslib) can you try defining `lucene` as your knn engine.

My problem has been resolved after this index mapping. Thank you @martin-gaievski 

```
  "mappings": {
    "properties": {
      "text_embedding": {
        "type": "nested",
        "properties": {
          "knn": {
            "type": "knn_vector",
            "dimension": 768,
            "method": {
              "name": "hnsw",
              "engine": "lucene"
            }
          }
        }
      }
    }
  }
```

**Comment by IanMenendez** [comment]
Changing the index mapping as it was suggested worked. But I still think OS should not crash the cluster if **libstdc++.so.6** is not found. It should catch the exception and throw an error

**Comment by CorentinLimier** [comment]
Any update on this issue ? I had a similar error (this time when indexing the documents on an index that uses faiss engine) 

```
java.lang.UnsatisfiedLinkError: /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_faiss_avx2.so: /usr/share/opensearch/data/ml_cache/pytorch/1.13.1-cpu-precxx11-linux-x86_64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_faiss_avx2.so) 
```

Solution to switch on Lucene doesn't work in my case because of https://github.com/opensearch-project/k-NN/issues/2347

Opensearch version on my cluster is 2.17

**Comment by heemin32** [comment]
@CorentinLimier Could you confirm if the issue happen when you use knn field directly without neural?

**Comment by CorentinLimier** [comment]
@heemin32 Sadly I can't. In my initial message I said that it was when indexing but this might be untrue : cluster was already down at that time because of this issue, which could occur after a neural query. 

We rollbacked the index to lucene engine because it happened on a production cluster. Switching all the searches from neural to knn field would be too costly.

**Comment by 0ctopus13prime** [comment]
@IanMenendez 
Hi, the linking error (`GLIBCXX_3.4.21 not found) arises because it fails to look up the symbol in GCC standard library.
This indicates that `libstdc++.so` file does not have the required symbol KNN shared library is looking for.

So the hot fix you can take is that build a new image based on the one that you're using and upgrade GCC to 7 inside. (actually it will work any version later than 5)
```
sudo yum install centos-release-scl
sudo yum install devtoolset-7-gcc devtoolset-7-gcc-c++
scl enable devtoolset-7 bash
```

Could you share the output of running `g++ --version` within container?

**Comment by CorentinLimier** [comment]
@0ctopus13prime awesome, thanks a lot for the lead, I will try that and tell you if it works + the output of `g++ --version` before and after

One question though, from the logs I can see that it uses libstdc++.so.6 from this path : `/usr/share/opensearch/data/ml_cache/pytorch/1.13.1-cpu-precxx11-linux-x86_64/libstdc++.so.6`

Full log : 
```
java.lang.UnsatisfiedLinkError: /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_faiss_avx2.so: /usr/share/opensearch/data/ml_cache/pytorch/1.13.1-cpu-precxx11-linux-x86_64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_faiss_avx2.so) 
```

Would updating the image and installing another version of libstdc++.so.6 fix the one that is used by opensearch there ? 

Thanks 🙏

**Comment by peterzhuamazon** [comment]
In 2.16 we switch from centos7 (glibc 2.17 gcc9) as it deprecated, and switch to AL2 (gblic 2.26 gcc10) for the build image.

It is well-documented here: 
* https://github.com/opensearch-project/opensearch-build/issues/4379 (cc: @junqiu-lei who worked on the AL2 gcc10 changes)

In 2.19 we plan to upgrade to gcc 13 for a new knn feature soon: 
* https://github.com/opensearch-project/opensearch-build/issues/5226

In June 2025 we plan to move again from AL2 to Almalinux8 (glibc 2.28 gcc11/13) due to AL2 deprecation.

**Comment by peterzhuamazon** [comment]
The issue here is very similar on libstdc++ here:
* https://github.com/opensearch-project/ml-commons/issues/2563

cc: @ylwu-amzn

**Comment by austintlee** [comment]
I just hit this error (and it crashed my cluster) on 2.19.1.  I'm running OpenSearch 2.19.1 on Ubuntu 24.04.2.

**Comment by joseluisgonzalezca** [comment]
I'm having the same issue with Opensearch v2.17.1 with Docker. After changing `LD_LIBRARY_PATH` environment variable like `LD_LIBRARY_PATH="/usr/lib64/libstdc++.so.6:$LD_LIBRARY_PATH"`, everything is working as expected.

**Comment by TheBigK02** [comment]
I fixed it as well. But wouldnt it be beneficial to just update the packaghed libstdc++.so.6 that you dont run into this issue anymore? This issue is one year old and it doesnt have to be that every new installation runs into this issue.
