### ISSUE TITLE
[BUG] RAG processor throws null pointer exception

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons#2983]
**What is the bug?**
Run RAG processor on multi-node cluster without dedicated master node. Can see such error
```
Cannot invoke "java.lang.Integer.intValue()" because "this.interactionSize" is null
```

**How can one reproduce the bug?**
1. Set up multi-node cluster with 3 nodes, all nodes have master and data role
2. Run RAG processor

**What is the expected behavior?**
Should not throw exception

**What is your host/environment?**
 - OS: Linux
 - Version 2.15

**Do you have any screenshots?**
No

**Do you have any additional context?**
Log
```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.interactionSize" is null
    at org.opensearch.searchpipelines.questionanswering.generative.ext.GenerativeQAParameters.writeTo(GenerativeQAParameters.java:197)
    at org.opensearch.searchpipelines.questionanswering.generative.ext.GenerativeQAParamExtBuilder.writeTo(GenerativeQAParamExtBuilder.java:75)
```

**Comment by ylwu-amzn** [comment]
Sure, assigned to you @pyek-bot
