### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/ml-commons#361]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [ ] Passing CI on Windows
- [ ] Documentation

**Comment by bbarani** [comment]
@ylwu-amzn @sean-zheng-amazon Can you please update the current status?

**Comment by ylwu-amzn** [comment]
@bbarani , thanks for reminding, looking this now. 
Can you share some action items we should do to support windows? Or maybe some example ?

**Comment by ylwu-amzn** [comment]
Never mind, I found SQL team has done that. Will refer to SQL plugin

**Comment by ylwu-amzn** [comment]
#504

**Comment by ylwu-amzn** [comment]
CustomModelITTests#testCustomModelWorkflow will fail to clean up local file cache. Test code run successfully, but test framework failed to cleanup temp local files.
```
at __randomizedtesting.SeedInfo.seed([D97C315DD114CE48]:0)
	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341)
	at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ylwu-amzn** [comment]
I reopen this issue as we should support " 100% parity in tests across all supported platforms, linux and windows.", refer to https://github.com/opensearch-project/opensearch-plugins/issues/95#issuecomment-1302678292

**Comment by peterzhuamazon** [comment]
Hi, just want to make sure this issue is closed, if all the tasks are completed.

Thanks.
